package main

import (
	"encoding/json"
	"fmt"
	"os"
	"strconv"
)

type AutoGenerated struct {
	Hits []struct {
		Index  string  `json:"_index"`
		Type   string  `json:"_type"`
		ID     string  `json:"_id"`
		Score  float64 `json:"_score"`
		Source struct {
		} `json:"source"`
	} `json:"hits"`
}

func main() {
	content, _ := os.ReadFile("/Users/tarzan/Documents/Code/kupu_go/gemini/parse_id/ids.json")
	parseJson(string(content))
}

func parseJson(d string) {
	var findTalentsOutput AutoGenerated
	err := json.Unmarshal([]byte(d), &findTalentsOutput)
	if err != nil {
		fmt.Println("Error:", err)
		return
	}
	for _, hit := range findTalentsOutput.Hits {
		atoi, _ := strconv.Atoi(hit.ID)
		fmt.Printf("%d,", atoi)
	}
}
